# Generated by Django 5.0 on 2023-12-27 16:43

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('char_class', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=1)),
                ('movement', models.IntegerField(default=30)),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('ability', jsonfield.fields.JSONField()),
            ],
        ),
    ]
