# Generated by Django 5.0 on 2023-12-27 22:51

import character_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, validators=[character_app.validators.validate_name]),
        ),
    ]
